# Generated by Django 4.1.6 on 2023-03-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="job_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
